spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans : true
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true

server :
  port: 8081
  servlet:
    context-path: /final/v1


logging:
  level:
    root: debug

